In [1]:
## Opening the datasus csv
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
df = pd.read_csv('/content/drive/MyDrive/tecnicas_datasus_pe/PE_2010_2019.csv', low_memory=False)
df

,Unnamed: 0,CONTADOR,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,DTNASC,IDADE,SEXO,...,VERSAOSIST,VERSAOSCB,ATESTADO,NUDIASOBCO,FONTES,TPRESGINFO,TPNIVELINV,NUDIASINF,FONTESINF,ALTCAUSA
0,0,1,1,2,15032010,0530,826.0,9041947.0,462,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,1,2,24122010,2045,826.0,15051922.0,488,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,3,1,2,25122010,1330,826.0,2111936.0,474,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,4,1,2,22052010,1515,826.0,5021956.0,454,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,5,1,2,4052010,2200,826.0,25031939.0,471,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605102,64290,1378517,1,2,13102019,1000,NaN,10011921.0,498,2,...,3.2.00,3.2,N188/N19/E114*I10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605103,64291,1378518,1,2,29102019,0715,NaN,29081968.0,451,1,...,3.2.00,3.2,R688/C509,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605104,64292,1378519,1,2,28102019,1145,NaN,24021934.0,485,2,...,3.2.00,3.2,A419/J189,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605105,64293,1378520,1,2,28102019,1255,NaN,10081916.0,503,1,...,3.2.00,3.2,C349,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605106,64294,1378521,1,2,1112019,0820,NaN,2091928.0,491,2,...,3.2.00,3.2,I460/E872/A418,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## Determining the percentage of non null content for each column

len_col = df.shape[0]
for col in list(df.keys()):
  total_nonNull=round(100*df[col].count()/len_col,2)
  print('Column {} has {} % of non null values'.format(col,total_nonNull))

In [4]:
## Defining the interest columns of the dataframe

interest_columns = ['LINHAA', 'LINHAB', 'LINHAC', 'LINHAD', 'LINHAII', 'CAUSABAS', 'CAUSABAS_O', 'ANO_O', 'ESTADO', 'CODMUNRES','CODMUNOCOR']

In [5]:
df2 = df[interest_columns]
df2

,LINHAA,LINHAB,LINHAC,LINHAD,LINHAII,CAUSABAS,CAUSABAS_O,ANO_O,ESTADO,CODMUNRES,CODMUNOCOR
0,*R688,*K729,NaN,NaN,*C240,K729,K729,2010,PE,260345,260345
1,*E86X,NaN,NaN,NaN,NaN,E86,E86,2010,PE,261020,261020
2,*E872,*E14X,NaN,NaN,NaN,E148,E14,2010,PE,261020,261020
3,*R092,*I10X,*E148,*M318,NaN,E148,E148,2010,PE,260190,260190
4,*I469,*I509,*E874,NaN,NaN,E874,E874,2010,PE,260005,260005
...,...,...,...,...,...,...,...,...,...,...,...
605102,*N188,*N19X,*E114,NaN,*I10X,E107,E107,2019,PE,260010,260010
605103,*R688,*C509,NaN,NaN,NaN,C509,C509,2019,PE,260690,260010
605104,*A419,*J189,NaN,NaN,NaN,J189,J189,2019,PE,260010,260010
605105,*C349,NaN,NaN,NaN,NaN,C349,C349,2019,PE,261280,260010
605106,*I460,*E872,*A418,NaN,NaN,A418,A418,2019,PE,260560,260010

In [6]:
## Evaluating state and year conditions required

filtro1 = df2['ESTADO'] == 'PE'
filtro2 = df2['ANO_O'] >= 2010
filtro3 = df2['ANO_O'] <= 2019
df2 = df2[filtro1]
df2 = df2[filtro2]
df2 = df2[filtro3]
df2

,LINHAA,LINHAB,LINHAC,LINHAD,LINHAII,CAUSABAS,CAUSABAS_O,ANO_O,ESTADO,CODMUNRES,CODMUNOCOR
0,*R688,*K729,NaN,NaN,*C240,K729,K729,2010,PE,260345,260345
1,*E86X,NaN,NaN,NaN,NaN,E86,E86,2010,PE,261020,261020
2,*E872,*E14X,NaN,NaN,NaN,E148,E14,2010,PE,261020,261020
3,*R092,*I10X,*E148,*M318,NaN,E148,E148,2010,PE,260190,260190
4,*I469,*I509,*E874,NaN,NaN,E874,E874,2010,PE,260005,260005
...,...,...,...,...,...,...,...,...,...,...,...
605102,*N188,*N19X,*E114,NaN,*I10X,E107,E107,2019,PE,260010,260010
605103,*R688,*C509,NaN,NaN,NaN,C509,C509,2019,PE,260690,260010
605104,*A419,*J189,NaN,NaN,NaN,J189,J189,2019,PE,260010,260010
605105,*C349,NaN,NaN,NaN,NaN,C349,C349,2019,PE,261280,260010
605106,*I460,*E872,*A418,NaN,NaN,A418,A418,2019,PE,260560,260010

In [32]:
## Evaluating cause of death counting

death_cause = set(df2['CAUSABAS']) ## 'CAUSABAS' column was selected as cause of death since it is defined as the basic cause of death in the database
death_cause_count = {}
death_cause_order = {}
for i in death_cause:
  death_cause_count[i] = 0

for i in df2['CAUSABAS']:
  death_cause_count[i]+=1

for i in sorted(death_cause_count, key = death_cause_count.get, reverse=True):
    death_cause_order[i]=death_cause_count[i]
print(death_cause_order)

{'I219': 55374, 'X954': 19994, 'J988': 19534, 'E149': 18999, 'I64': 15531, 'J189': 15516, 'R98': 11416, 'I694': 10603, 'I10': 10230, 'J449': 9960, 'I678': 9480, 'I619': 9028, 'C349': 8838, 'R99': 7748, 'N390': 7144, 'C61': 7040, 'A419': 7033, 'C509': 6708, 'I110': 6287, 'G309': 5334, 'C169': 5255, 'E142': 4669, 'I251': 4545, 'I500': 4447, 'J440': 4073, 'E46': 3885, 'J180': 3768, 'I119': 3744, 'I509': 3696, 'I269': 3653, 'K703': 3546, 'E145': 3430, 'F102': 3423, 'A09': 3403, 'C229': 3226, 'K746': 3142, 'I420': 3029, 'C539': 2919, 'Y349': 2903, 'C80': 2880, 'A162': 2867, 'X994': 2795, 'C159': 2651, 'X959': 2616, 'E148': 2610, 'C259': 2556, 'K769': 2555, 'B207': 2440, 'C189': 2423, 'J181': 2413, 'V299': 2320, 'X950': 2313, 'I609': 2279, 'I517': 2166, 'X958': 2074, 'N189': 1988, 'J159': 1975, 'K709': 1937, 'W789': 1933, 'J439': 1928, 'K920': 1907, 'J690': 1895, 'I259': 1893, 'R54': 1847, 'I710': 1831, 'C710': 1814, 'V093': 1802, 'R092': 1786, 'V892': 1778, 'C56': 1716, 'K550': 1559, 'N179': 1544, 'E119': 1514, 'C329': 1512, 'X700': 1500, 'B651': 1462, 'C20': 1415, 'C679': 1408, 'W190': 1347, 'E147': 1346, 'Y340': 1291, 'Y004': 1289, 'I120': 1281, 'C859': 1242, 'W199': 1242, 'P369': 1241, 'G20': 1195, 'E669': 1194, 'X934': 1172, 'I255': 1147, 'I739': 1137, 'R688': 1135, 'C55': 1108, 'C719': 1106, 'J459': 1104, 'I698': 1097, 'Q249': 1062, 'K704': 1055, 'J188': 1054, 'X599': 1050, 'K566': 1049, 'C64': 1019, 'C900': 1006, 'K922': 996, 'N19': 990, 'K859': 985, 'I422': 976, 'P000': 951, 'K729': 946, 'V499': 943, 'E141': 934, 'C220': 913, 'D649': 901, 'B200': 892, 'I802': 885, 'V234': 883, 'B572': 876, 'C920': 868, 'C260': 861, 'C23': 847, 'L089': 828, 'K650': 828, 'L89': 827, 'C249': 826, 'I48': 822, 'G409': 820, 'V284': 813, 'I501': 811, 'A46': 806, 'C250': 803, 'X990': 801, 'J81': 788, 'E43': 787, 'N12': 777, 'F172': 775, 'C221': 760, 'J448': 728, 'M623': 720, 'J984': 706, 'C541': 699, 'C109': 694, 'X999': 688, 'E112': 686, 'W698': 684, 'I429': 684, 'C760': 683, 'I499': 681, 'I713': 675, 'E86': 666, 'B208': 654, 'C449': 645, 'W780': 618, 'I248': 613, 'J960': 609, 'C029': 605, 'Y344': 597, 'G809': 595, 'J969': 582, 'V294': 577, 'C069': 561, 'I519': 553, 'P001': 550, 'V031': 533, 'I350': 524, 'W748': 522, 'X998': 521, 'C959': 518, 'B227': 513, 'V899': 508, 'V021': 500, 'B182': 494, 'I250': 494, 'Y348': 493, 'Q899': 491, 'P011': 484, 'E140': 482, 'K700': 481, 'P027': 475, 'I709': 470, 'J841': 464, 'Y009': 457, 'K830': 456, 'E788': 453, 'I132': 449, 'I639': 449, 'P220': 442, 'J22': 441, 'N40': 435, 'V244': 428, 'I672': 427, 'C73': 421, 'N289': 420, 'I711': 416, 'P229': 413, 'C762': 411, 'C439': 408, 'N038': 404, 'C798': 404, 'J90': 400, 'B201': 397, 'E126': 396, 'C140': 396, 'G122': 394, 'C910': 391, 'K275': 388, 'B24': 387, 'W194': 385, 'C19': 384, 'W870': 384, 'W180': 383, 'V099': 379, 'P072': 378, 'V224': 374, 'K852': 364, 'I620': 361, 'J869': 360, 'N10': 358, 'R960': 354, 'K254': 352, 'N039': 352, 'B909': 349, 'Q909': 349, 'C419': 348, 'I38': 337, 'C780': 337, 'F03': 335, 'I139': 334, 'C269': 333, 'E889': 328, 'K819': 325, 'J441': 325, 'E668': 323, 'A418': 322, 'K850': 320, 'X952': 319, 'I258': 316, 'C383': 315, 'X955': 312, 'Y000': 312, 'B99': 311, 'P219': 310, 'P070': 309, 'I891': 309, 'I129': 308, 'K810': 306, 'I279': 306, 'K760': 306, 'I059': 304, 'P010': 304, 'V485': 301, 'K802': 298, 'M321': 296, 'C499': 294, 'I340': 293, 'I330': 291, 'I850': 287, 'K750': 286, 'K562': 285, 'P210': 284, 'W189': 282, 'E118': 280, 'P240': 279, 'K350': 279, 'E878': 277, 'Y218': 274, 'N200': 273, 'D619': 270, 'K701': 270, 'Q000': 269, 'V486': 266, 'K767': 265, 'W749': 261, 'Y008': 258, 'I442': 257, 'G919': 256, 'I714': 255, 'A150': 254, 'V289': 254, 'E115': 253, 'C788': 253, 'G049': 253, 'C187': 252, 'V274': 252, 'V041': 249, 'D689': 246, 'K264': 245, 'K578': 245, 'A169': 245, 'G009': 244, 'K290': 243, 'P021': 242, 'K766': 242, 'D699': 242, 'X680': 241, 'E109': 240, 'J46': 240, 'C170': 239, 'A279': 238, 'I712': 237, 'C729': 231, 'K659': 231, 'I358': 230, 'X709': 229, 'I080': 228, 'E872': 228, 'P77': 227, 'G931': 226, 'I213': 225, 'A199': 225, 'A91': 225, 'I210': 223, 'I099': 223, 'C911': 223, 'J989': 222, 'C763': 221, 'I249': 218, 'M869': 215, 'C819': 214, 'K255': 213, 'Y294': 211, 'C609': 210, 'P280': 207, 'W879': 207, 'P015': 205, 'E107': 201, 'W874': 201, 'E117': 201, 'N288': 196, 'Q248': 194, 'I693': 194, 'K593': 193, 'Q336': 193, 'I718': 192, 'I671': 192, 'V99': 192, 'Q039': 191, 'W738': 190, 'J47': 190, 'K768': 189, 'C921': 189, 'P239': 187, 'I461': 187, 'Y299': 187, 'I426': 186, 'D469': 185, 'X708': 185, 'V494': 183, 'V239': 180, 'G301': 180, 'C749': 179, 'X930': 178, 'J158': 177, 'C01': 175, 'C240': 170, 'P209': 170, 'V235': 169, 'D539': 167, 'J069': 166, 'R570': 164, 'K274': 164, 'P399': 164, 'J182': 163, 'B573': 163, 'G039': 162, 'C787': 161, 'G936': 161, 'I638': 157, 'V204': 156, 'I131': 155, 'I779': 155, 'X689': 155, 'C482': 154, 'K404': 154, 'K403': 154, 'I348': 153, 'E108': 153, 'D696': 153, 'K803': 152, 'I674': 152, 'V229': 151, 'D571': 150, 'P073': 149, 'V296': 149, 'I130': 149, 'V295': 148, 'N188': 148, 'P008': 148, 'K579': 147, 'I749': 147, 'B659': 147, 'V489': 146, 'V435': 146, 'K720': 145, 'X704': 145, 'C716': 144, 'V445': 144, 'X944': 144, 'Y044': 144, 'C119': 142, 'C443': 141, 'Q049': 141, 'Y219': 141, 'C519': 139, 'C139': 139, 'K631': 138, 'V436': 138, 'I719': 137, 'C160': 137, 'X939': 137, 'C444': 136, 'C179': 135, 'Q793': 135, 'F329': 133, 'Q790': 132, 'I260': 132, 'E162': 132, 'V285': 132, 'Y838': 131, 'L97': 131, 'P269': 130, 'B169': 130, 'W878': 129, 'N309': 129, 'A920': 127, 'C211': 127, 'F109': 125, 'K460': 125, 'G710': 125, 'W060': 122, 'W790': 122, 'K564': 122, 'V249': 122, 'P969': 122, 'A049': 121, 'V800': 121, 'K800': 120, 'K265': 120, 'P249': 120, 'V446': 119, 'E146': 119, 'J219': 118, 'G939': 117, 'Y290': 117, 'C07': 116, 'N300': 116, 'K359': 115, 'R571': 115, 'X992': 114, 'I490': 114, 'I270': 113, 'J80': 112, 'K469': 112, 'K721': 111, 'E780': 111, 'C412': 110, 'G934': 110, 'G932': 110, 'J42': 109, 'B550': 108, 'W182': 107, 'Q913': 107, 'I319': 106, 'B349': 106, 'B206': 106, 'I421': 106, 'K565': 105, 'K259': 105, 'I702': 104, 'K409': 104, 'X914': 103, 'X740': 103, 'W130': 103, 'K560': 102, 'G35': 102, 'J980': 102, 'C786': 101, 'E101': 101, 'E116': 101, 'D320': 100, 'Y298': 100, 'X910': 100, 'C500': 99, 'X090': 99, 'C480': 98, 'K805': 98, 'E41': 98, 'Y200': 98, 'K271': 98, 'I209': 97, 'W100': 97, 'M069': 96, 'E110': 96, 'E111': 95, 'I615': 95, 'X589': 94, 'K439': 94, 'D70': 94, 'K37': 93, 'C180': 93, 'I351': 93, 'V199': 92, 'C629': 91, 'N498': 91, 'C851': 91, 'C059': 90, 'I679': 90, 'K831': 90, 'I514': 89, 'K420': 89, 'M319': 89, 'F100': 88, 'P291': 88, 'W699': 88, 'N133': 88, 'J939': 87, 'P271': 87, 'A502': 87, 'C549': 87, 'C402': 87, 'A483': 86, 'J851': 85, 'C785': 85, 'W010': 85, 'G405': 85, 'A86': 85, 'I200': 85, 'G610': 84, 'K279': 84, 'G319': 84, 'D65': 83, 'L984': 83, 'G410': 82, 'V134': 82, 'K590': 82, 'P002': 81, 'Q210': 81, 'J961': 81, 'J709': 81, 'X991': 81, 'P038': 81, 'Q02': 80, 'Q897': 80, 'V495': 80, 'V496': 80, 'P285': 80, 'D479': 80, 'C795': 79, 'W134': 79, 'Q213': 77, 'O994': 77, 'L031': 77, 'P009': 77, 'I211': 76, 'V298': 76, 'P071': 76, 'I050': 76, 'V092': 75, 'C751': 75, 'K297': 75, 'L039': 75, 'K759': 75, 'X584': 75, 'C411': 74, 'V245': 74, 'D648': 74, 'M009': 74, 'N399': 74, 'C410': 73, 'K20': 72, 'A394': 72, 'K219': 72, 'V194': 72, 'Q390': 72, 'J852': 71, 'O96': 71, 'X590': 71, 'A90': 71, 'L024': 71, 'C508': 71, 'C445': 71, 'Q250': 70, 'J40': 70, 'C845': 70, 'N139': 70, 'Q043': 70, 'K801': 70, 'I424': 70, 'E102': 69, 'P832': 69, 'E039': 69, 'I229': 69, 'W849': 69, 'I516': 68, 'C950': 68, 'N151': 68, 'I738': 68, 'I498': 68, 'K929': 68, 'E789': 67, 'C168': 67, 'C717': 67, 'E100': 67, 'I359': 67, 'A309': 67, 'I99': 67, 'C492': 67, 'G312': 66, 'R64': 66, 'P012': 66, 'K658': 66, 'C833': 65, 'Q211': 65, 'V685': 65, 'G822': 64, 'E440': 64, 'B570': 64, 'V439': 64, 'A153': 64, 'W198': 64, 'F106': 64, 'A412': 63, 'I803': 63, 'G629': 63, 'B222': 62, 'I618': 62, 'J981': 62, 'E875': 62, 'X951': 62, 'V475': 61, 'P968': 61, 'K661': 61, 'C049': 61, 'C929': 61, 'X995': 60, 'K430': 59, 'C761': 59, 'N180': 59, 'E105': 59, 'C538': 59, 'W730': 58, 'F209': 58, 'I829': 58, 'K559': 58, 'I518': 58, 'I691': 58, 'W740': 58, 'W799': 57, 'K739': 57, 'V449': 57, 'Y094': 57, 'X099': 57, 'O998': 57, 'D471': 57, 'R100': 56, 'K529': 56, 'I252': 56, 'C52': 56, 'G060': 56, 'I830': 55, 'K860': 55, 'X957': 55, 'K461': 55, 'K449': 55, 'P025': 55, 'X080': 55, 'C793': 54, 'I313': 54, 'N119': 54, 'C341': 54, 'A085': 54, 'V225': 54, 'C340': 53, 'C481': 53, 'P020': 53, 'D259': 53, 'C414': 53, 'C182': 53, 'X940': 52, 'I428': 52, 'I743': 52, 'R048': 52, 'I069': 52, 'D759': 52, 'J110': 52, 'E059': 52, 'X760': 52, 'C348': 51, 'Y210': 51, 'Q442': 51, 'E144': 51, 'Q792': 51, 'X919': 51, 'C447': 50, 'X790': 50, 'C099': 50, 'E127': 50, 'R95': 50, 'K421': 49, 'V498': 49, 'V209': 49, 'I629': 49, 'P290': 48, 'Y209': 48, 'I342': 48, 'P201': 48, 'F103': 48, 'I253': 48, 'V144': 48, 'X918': 48, 'W019': 48, 'R090': 47, 'C924': 47, 'V279': 47, 'E785': 47, 'J688': 47, 'I716': 47, 'V124': 47, 'F99': 47, 'I872': 47, 'X040': 46, 'X938': 46, 'Q203': 46, 'V484': 46, 'Y049': 46, 'E870': 46, 'Y098': 46, 'J129': 46, 'A310': 46, 'K269': 46, 'C837': 46, 'W200': 46, 'Y86': 46, 'J398': 45, 'Y189': 45, 'I608': 45, 'I839': 45, 'R58': 45, 'C241': 45, 'Q917': 45, 'J64': 44, 'V280': 44, 'M318': 44, 'C162': 43, 'N136': 43, 'I212': 43, 'D849': 43, 'V698': 43, 'C579': 43, 'X690': 43, 'W139': 42, 'K858': 42, 'P022': 42, 'K429': 42, 'V476': 42, 'Y099': 42, 'Y872': 42, 'G042': 42, 'J698': 42, 'V189': 41, 'N319': 41, 'M349': 41, 'R568': 41, 'C772': 41, 'G700': 41, 'I309': 41, 'B199': 41, 'X800': 41, 'X804': 41, 'I443': 41, 'M199': 41, 'C919': 40, 'K660': 40, 'A499': 40, 'K251': 40, 'O995': 40, 'Y199': 40, 'X701': 40, 'F101': 40, 'K804': 40, 'K921': 40, 'E840': 39, 'K851': 39, 'X699': 39, 'P243': 39, 'P200': 39, 'P039': 39, 'W770': 39, 'K250': 39, 'C969': 39, 'G404': 39, 'J860': 39, 'A500': 39, 'C578': 39, 'X974': 39, 'W708': 39, 'B205': 39, 'Q059': 39, 'X794': 39, 'K319': 39, 'C218': 39, 'Y835': 39, 'X935': 38, 'G419': 38, 'X780': 38, 'V275': 38, 'C829': 38, 'I214': 38, 'C184': 38, 'I729': 38, 'B171': 38, 'C150': 38, 'W788': 37, 'W179': 37, 'C97': 37, 'C699': 37, 'I692': 37, 'Y836': 37, 'Q234': 37, 'K318': 37, 'J985': 37, 'W069': 36, 'I859': 36, 'I690': 36, 'C400': 36, 'B218': 36, 'W792': 36, 'D487': 36, 'C442': 36, 'N281': 36, 'C902': 36, 'Y260': 35, 'R961': 35, 'C300': 35, 'Q042': 35, 'A060': 35, 'E441': 35, 'O85': 35, 'K702': 35, 'C759': 34, 'O622': 34, 'Q079': 34, 'A379': 34, 'Y899': 34, 'F179': 34, 'M819': 34, 'C65': 34, 'W184': 34, 'O882': 34, 'W070': 34, 'A94': 34, 'W784': 34, 'W694': 34, 'C343': 34, 'J677': 34, 'Y850': 33, 'B575': 33, 'Y339': 33, 'X610': 33, 'A35': 33, 'V029': 33, 'G09': 33, 'C696': 33, 'A183': 33, 'Y834': 32, 'A409': 32, 'V270': 32, 'A810': 32, 'J678': 32, 'I959': 32, 'E874': 32, 'J849': 32, 'Q438': 32, 'K861': 32, 'O141': 32, 'K431': 32, 'J708': 31, 'Q798': 31, 'A390': 31, 'N429': 31, 'Q054': 31, 'F799': 31, 'G825': 31, 'E871': 31, 'E835': 31, 'B451': 31, 'Y040': 31, 'K572': 31, 'P031': 31, 'Y330': 31, 'K295': 31, 'P288': 31, 'C720': 31, 'M329': 31, 'B91': 31, 'C792': 31, 'V230': 30, 'C678': 30, 'E752': 30, 'C310': 30, 'C33': 30, 'Y180': 30, 'H669': 30, 'Q870': 30, 'V039': 30, 'K221': 30, 'W012': 30, 'Q019': 30, 'W109': 30, 'C490': 30, 'X640': 29, 'X749': 29, 'B582': 29, 'C178': 29, 'D694': 29, 'J111': 29, 'C765': 29, 'Q602': 29, 'O721': 29, 'Q419': 29, 'D509': 29, 'D352': 29, 'I809': 29, 'K740': 29, 'I471': 29, 'P159': 29, 'P788': 29, 'L511': 29, 'A270': 29, 'G001': 29, 'C384': 28, 'I820': 28, 'W174': 28, 'I089': 28, 'C783': 28, 'W104': 28, 'K829': 28, 'X720': 28, 'C181': 28, 'B004': 28, 'W204': 28, 'P251': 28, 'B162': 28, 'I311': 28, 'J150': 28, 'D589': 28, 'I771': 28, 'G308': 28, 'D381': 28, 'B220': 28, 'V879': 27, 'C320': 27, 'V675': 27, 'N009': 27, 'M625': 27, 'I081': 27, 'B029': 27, 'J942': 27, 'D593': 27, 'G318': 27, 'C227': 27, 'C163': 27, 'P024': 27, 'Q391': 27, 'C770': 27, 'P700': 27, 'E15': 27, 'K754': 27, 'C183': 27, 'C148': 26, 'K276': 26, 'C768': 26, 'B571': 26, 'R579': 26, 'B259': 26, 'W744': 26, 'P53': 26, 'K638': 26, 'D075': 26, 'D570': 26, 'K513': 26, 'Q212': 26, 'I832': 26, 'C437': 26, 'W782': 26, 'K220': 26, 'C37': 26, 'P059': 26, 'L022': 26, 'C796': 26, 'C839': 26, 'C261': 26, 'O159': 26, 'I723': 25, 'K808': 25, 'C409': 25, 'P293': 25, 'W875': 25, 'K745': 25, 'C399': 25, 'I720': 25, 'P780': 25, 'B012': 25, 'I632': 25, 'I728': 25, 'F192': 25, 'D62': 25, 'G98': 25, 'A165': 25, 'I301': 25, 'Q031': 25, 'L038': 25, 'C251': 25, 'C210': 25, 'V049': 25, 'L080': 25, 'F019': 25, 'I472': 25, 'K561': 25, 'G959': 25, 'X997': 24, 'I349': 24, 'V184': 24, 'C689': 24, 'Q431': 24, 'K639': 24, 'Q433': 24, 'V870': 24, 'R578': 24, 'Q601': 24, 'Y883': 24, 'V686': 24, 'C158': 24, 'K222': 24, 'C790': 24, 'N170': 24, 'I083': 24, 'C700': 24, 'W168': 24, 'Y871': 24, 'X978': 24, 'I092': 24, 'W138': 24, 'D400': 24, 'C494': 23, 'Q251': 23, 'P361': 23, 'O150': 23, 'K632': 23, 'Y002': 23, 'I715': 23, 'J450': 23, 'C342': 23, 'C380': 23, 'Q200': 23, 'V139': 23, 'K764': 23, 'E660': 23, 'C321': 23, 'X748': 23, 'V809': 23, 'X928': 23, 'I352': 23, 'W860': 23, 'K272': 23, 'Q048': 23, 'C767': 23, 'I607': 23, 'N209': 23, 'F059': 22, 'N280': 22, 'I700': 22, 'X209': 22, 'Y244': 22, 'V293': 22, 'P013': 22, 'Y090': 22, 'X094': 22, 'W747': 22, 'M139': 22, 'I81': 22, 'X239': 22, 'Q224': 22, 'K811': 22, 'I409': 22, 'K570': 22, 'I724': 22, 'X744': 22, 'W062': 22, 'Y208': 22, 'E888': 22, 'V205': 22, 'B210': 22, 'V586': 22, 'M600': 22, 'C927': 22, 'Q410': 21, 'I019': 21, 'C692': 21, 'C791': 21, 'Q613': 21, 'P529': 21, 'K633': 21, 'W809': 21, 'B178': 21, 'D430': 21, 'Q871': 21, 'O152': 21, 'X649': 21, 'C718': 21, 'I00': 21, 'K256': 21, 'I058': 21, 'I091': 21, 'N26': 21, 'Y240': 21, 'W499': 21, 'C252': 21, 'G800': 21, 'D683': 21, 'X840': 21, 'X718': 20, 'K509': 20, 'K260': 20, 'L021': 20, 'F171': 20, 'A509': 20, 'Y269': 20, 'K818': 20, 'Q289': 20, 'Q273': 20, 'K270': 20, 'Q894': 20, 'I510': 20, 'X948': 20, 'P023': 20, 'P298': 20, 'O996': 20, 'M348': 20, 'C495': 20, 'Q780': 20, 'M359': 20, 'W697': 20, 'O903': 20, 'N132': 20, 'B019': 20, 'V290': 19, 'Q245': 19, 'C491': 19, 'C186': 19, 'L930': 19, 'C258': 19, 'X682': 19, 'L989': 19, 'C268': 19, 'W877': 19, 'I740': 19, 'E854': 19, 'E138': 19, 'I090': 19, 'D376': 19, 'F104': 19, 'O149': 19, 'A178': 19, 'V480': 19, 'V281': 19, 'G311': 19, 'M469': 19, 'C080': 19, 'N201': 19, 'Y214': 19, 'G300': 19, 'X799': 19, 'V699': 19, 'G938': 19, 'C915': 19, 'I633': 19, 'D610': 19, 'D180': 19, 'W144': 18, 'C901': 18, 'I613': 18, 'C161': 18, 'X707': 18, 'C254': 18, 'J410': 18, 'J60': 18, 'Y249': 18, 'P38': 18, 'W840': 18, 'N110': 18, 'M868': 18, 'D45': 18, 'B232': 18, 'Y048': 18, 'N492': 18, 'W800': 18, 'F322': 18, 'A929': 18, 'K573': 18, 'V444': 18, 'Y001': 18, 'D377': 18, 'O95': 18, 'C764': 18, 'W192': 18, 'I051': 18, 'C222': 18, 'V434': 17, 'N049': 17, 'C469': 17, 'V479': 17, 'P241': 17, 'Q257': 17, 'Q878': 17, 'G839': 17, 'P005': 17, 'C248': 17, 'L029': 17, 'Y341': 17, 'E859': 17, 'Q338': 17, 'X684': 17, 'Q999': 17, 'W140': 17, 'N059': 17, 'M629': 17, 'Y204': 17, 'Q439': 17, 'Q411': 17, 'C089': 17, 'Y841': 17, 'E40': 17, 'V240': 17, 'E831': 17, 'B203': 17, 'P044': 17, 'B690': 17, 'J13': 17, 'L088': 17, 'K252': 17, 'I511': 17, 'B202': 17, 'K610': 17, 'E52': 17, 'A159': 17, 'A170': 17, 'Q614': 17, 'C433': 17, 'B189': 17, 'C446': 16, 'C66': 16, 'X619': 16, 'V645': 16, 'C459': 16, 'V264': 16, 'M313': 16, 'W678': 16, 'I776': 16, 'N419': 16, 'I513': 16, 'N359': 16, 'J680': 16, 'Q606': 16, 'I310': 16, 'V878': 16, 'C051': 16, 'C319': 16, 'V091': 16, 'K298': 16, 'G408': 16, 'P393': 16, 'V129': 16, 'E782': 16, 'I256': 16, 'W690': 16, 'V196': 16, 'A99': 16, 'E137': 16, 'X970': 16, 'P041': 16, 'P960': 16, 'B948': 16, 'K351': 16, 'I722': 16, 'B159': 15, 'N159': 15, 'G930': 15, 'V694': 15, 'M628': 15, 'E876': 15, 'I312': 15, 'Y007': 15, 'K839': 15, 'L120': 15, 'C448': 15, 'D688': 15, 'K401': 15, 'C435': 15, 'X702': 15, 'C479': 15, 'K261': 15, 'C830': 15, 'G808': 15, 'O001': 15, 'J982': 15, 'W170': 15, 'V220': 15, 'A084': 15, 'L932': 15, 'X849': 15, 'P964': 15, 'Q070': 15, 'G909': 15, 'X769': 15, 'P60': 15, 'G459': 15, 'C039': 15, 'G10': 15, 'E106': 15, 'M809': 15, 'W080': 15, 'K122': 14, 'M311': 14, 'G589': 14, 'Q230': 14, 'N709': 14, 'I423': 14, 'K761': 14, 'W149': 14, 'V874': 14, 'I515': 14, 'O711': 14, 'E880': 14, 'A399': 14, 'Q446': 14, 'E274': 14, 'E781': 14, 'D432': 14, 'X798': 14, 'Q794': 14, 'V090': 14, 'Y831': 14, 'V585': 14, 'J384': 14, 'I308': 14, 'B377': 14, 'E139': 14, 'N308': 14, 'K758': 14, 'G119': 14, 'P003': 14, 'X949': 14, 'Y084': 14, 'C323': 14, 'A490': 14, 'I425': 14, 'O993': 14, 'J151': 14, 'K296': 14, 'Q225': 14, 'I254': 13, 'G403': 13, 'Q447': 13, 'K519': 13, 'C493': 13, 'V893': 13, 'D591': 13, 'Y119': 13, 'E055': 13, 'V746': 13, 'G628': 13, 'P579': 13, 'Y034': 13, 'I778': 13, 'C188': 13, 'B211': 13, 'B212': 13, 'E114': 13, 'C050': 13, 'M866': 13, 'I614': 13, 'M726': 13, 'C838': 13, 'C715': 13, 'Y342': 13, 'Y190': 13, 'P833': 13, 'Q359': 13, 'A161': 13, 'I741': 13, 'C711': 13, 'X120': 13, 'V877': 13, 'I744': 13, 'I828': 13, 'A182': 13, 'Q220': 13, 'X429': 13, 'P916': 13, 'B018': 13, 'J329': 13, 'K229': 13, 'I300': 13, 'C728': 13, 'V546': 13, 'D489': 13, 'C504': 13, 'W670': 13, 'C152': 13, 'C154': 13, 'O100': 13, 'I447': 13, 'Y334': 13, 'Q639': 13, 'B190': 12, 'C438': 12, 'D761': 12, 'D530': 12, 'K743': 12, 'A059': 12, 'P004': 12, 'C328': 12, 'W872': 12, 'P550': 12, 'E778': 12, 'G92': 12, 'V200': 12, 'X979': 12, 'Y005': 12, 'P614': 12, 'C440': 12, 'N739': 12, 'I459': 12, 'C835': 12, 'Y264': 12, 'J09': 12, 'C680': 12, 'I745': 12, 'J118': 12, 'C913': 12, 'K413': 12, 'P299': 12, 'B559': 12, 'I060': 12, 'V030': 12, 'W178': 12, 'P289': 12, 'E131': 12, 'K414': 12, 'D728': 12, 'K266': 12, 'V804': 12, 'K820': 12, 'K863': 12, 'K292': 12, 'P749': 12, 'K228': 12, 'N738': 12, 'G712': 12, 'D693': 12, 'G709': 12, 'K567': 12, 'K291': 12, 'D444': 12, 'G379': 12, 'N832': 12, 'C794': 12, 'E161': 12, 'V040': 12, 'D733': 12, 'V481': 12, 'Y039': 12, 'B658': 12, 'I071': 12, 'Y280': 12, 'J100': 12, 'K419': 12, 'V149': 12, 'W014': 12, 'L033': 12, 'I052': 11, 'O990': 11, 'V051': 11, 'Q204': 11, 'C957': 11, 'X084': 11, 'B92': 11, 'Y338': 11, 'F199': 11, 'Q339': 11, 'W208': 11, 'M314': 11, 'Y350': 11, 'L100': 11, 'C753': 11, 'R091': 11, 'Y830': 11, 'C009': 11, 'I630': 11, 'F149': 11, 'X688': 11, 'Q208': 11, 'Q789': 11, 'W209': 11, 'C090': 11, 'E640': 11, 'C574': 11, 'G360': 11, 'X705': 11, 'D059': 11, 'Y289': 11, 'J438': 11, 'W750': 11, 'W868': 11, 'L023': 11, 'X098': 11, 'N111': 11, 'Y839': 11, 'E169': 11, 'X299': 11, 'C945': 11, 'V684': 11, 'D464': 11, 'V291': 11, 'D001': 11, 'K868': 11, 'E143': 11, 'M303': 11, 'K571': 11, 'W148': 10, 'R02': 10, 'K717': 10, 'G310': 10, 'C172': 10, 'A190': 10, 'V953': 10, 'C675': 10, 'A410': 10, 'E049': 10, 'C530': 10, 'F107': 10, 'X588': 10, 'X953': 10, 'W854': 10, 'Q620': 10, 'I278': 10, 'K558': 10, 'I208': 10, 'K210': 10, 'N719': 10, 'C840': 10, 'V798': 10, 'B181': 10, 'D762': 10, 'P748': 10, 'X719': 10, 'I339': 10, 'Q642': 10, 'I636': 10, 'Q898': 10, 'C779': 10, 'V646': 10, 'P228': 10, 'W859': 10, 'W390': 10, 'D66': 10, 'V174': 10, 'R402': 10, 'J108': 10, 'X929': 10, 'F339': 10, 'X830': 10, 'Q423': 10, 'Y284': 10, 'N178': 10, 'Y110': 10, 'G723': 10, 'Q874': 10, 'J948': 10, 'B650': 10, 'I341': 10, 'E763': 10, 'V011': 10, 'G210': 10, 'X580': 10, 'K628': 10, 'P042': 10, 'V587': 10, 'G969': 10, 'Y201': 10, 'Q795': 10, 'F332': 10, 'V429': 10, 'W798': 10, 'Q256': 10, 'D291': 10, 'A879': 10, 'E249': 10, 'I831': 10, 'C060': 9, 'Q619': 9, 'W191': 9, 'W871': 9, 'P701': 9, 'C111': 9, 'C108': 9, 'P358': 9, 'R098': 9, 'G400': 9, 'P368': 9, 'V430': 9, 'C398': 9, 'F200': 9, 'K563': 9, 'D330': 9, 'E858': 9, 'Q218': 9, 'X956': 9, 'R268': 9, 'W195': 9, 'K710': 9, 'N321': 9, 'Q850': 9, 'P599': 9, 'V687': 9, 'D600': 9, 'W850': 9, 'K22

In [ ]:
## Transforming CSV file into a dictionary

import csv

with open('/content/drive/MyDrive/tecnicas_datasus_pe/CID_10_ILL.csv', mode='r') as CID_1:
    reader = csv.reader(CID_1)
    with open('CID_10N.csv', mode='w') as CID_2:
        writer = csv.writer(CID_2)
        CID_dict = {rows[0]:rows[1] for rows in reader}
        #print(CID_dict)

In [ ]:
## Returning the name of the disease based on the CID-10 code

CID_list = CID_dict.keys()
while True:
  x = input("Digite o código CID-10 para o qual você deseja saber a doença: ")
  x = x.upper()

  if x in CID_list:
    y = CID_dict[x]
    print("A doença referente ao código "+x+" na CID-10 é: "+y)
    break
  else:
    print("O código informado não consta na base de dados da CID-10.")

In [ ]:
## f) Identification of CID's chapter and CID's category by code
## Unified file

import chardet

def code_trat(x):
  n = len(x)
  x1 = x.replace(x[n-1], '')
  return x1

def cid_unificado():
  cid_unif = dict()
  with open('/content/drive/MyDrive/tecnicas_datasus_pe/CID-10-CAPITULOS.CSV', 'rb') as f:
      result = chardet.detect(f.read())
      
  cid_caps = pd.read_csv('/content/drive/MyDrive/tecnicas_datasus_pe/CID-10-CAPITULOS.CSV', encoding=result['encoding'], sep=';')
  cid_cat = pd.read_csv('/content/drive/MyDrive/tecnicas_datasus_pe/CID-10-CATEGORIAS.CSV', encoding=result['encoding'], sep=';')
  cid_subcat = pd.read_csv('/content/drive/MyDrive/tecnicas_datasus_pe/CID-10-SUBCATEGORIAS.CSV', encoding=result['encoding'], sep=';')

  cid_unif['CATINIC'] = cid_caps['CATINIC']
  cid_unif['CATFIM'] = cid_caps['CATFIM']
  cid_unif['DESCRICAO_CAP'] = cid_caps['DESCRICAO']
  cid_unif['CAT'] = cid_cat['CAT']
  cid_unif['DESCRICAO_CAT'] = cid_cat['DESCRICAO']
  cid_unif['SUBCAT'] = cid_subcat['SUBCAT']
  cid_unif['DESCRICAO_SUBCAT'] = cid_subcat['DESCRICAO']

  cid_unif = pd.DataFrame(cid_unif)
  cid_unif.to_csv('/content/drive/MyDrive/tecnicas_datasus_pe/CID-10_UNIFICADO.csv')


def cod_cid(code):
  cid_unificado()
  code1 = code_trat(code)
  cats = dict()
  caps = dict()
  disease = dict()

  cid_unif = pd.read_csv('/content/drive/MyDrive/tecnicas_datasus_pe/CID-10_UNIFICADO.csv')
  #display(cid_unif)

  #Chapter's, category's and subcategory's dicts from the corresponding CID
  aux = cid_unif.loc[:, ['CAT', 'DESCRICAO_CAT']]
  for cont, c in enumerate(aux['CAT']):
    cats[c] = aux['DESCRICAO_CAT'][cont]
  keys_cats = list(cats.keys())

  aux2 = cid_unif.loc[:, ['CATINIC', 'CATFIM', 'DESCRICAO_CAP']]
  
  aux3 = cid_unif.loc[:, ['SUBCAT', 'DESCRICAO_SUBCAT']]

  for cont, c in enumerate (aux2['DESCRICAO_CAP']):
    caps[c] = [aux2['CATINIC'][cont]]
    inic = keys_cats.index(aux2['CATINIC'][cont])
    fim = keys_cats.index(aux2['CATFIM'][cont])
    for j, value in enumerate(cats):
      if (j > inic) and (j <= fim):
        caps[c].append(value)
  
  #print(cats)
  #print(caps)
  
  #for k,v in caps.items():
   # print(f'{k}: {v}')

  #Identification of disease by CID's code
  disease['CODIGO'] = code
  for k,v in caps.items():
    if code1 in v:
      disease['CAPÍTULO'] = k
      break
  for k, v in cats.items():
    if code1 == k:
      disease['CATEGORIA'] = v
      break
  for cont, v in enumerate (aux3['SUBCAT']):
    if v == code:
      disease['SUBCATEGORIA'] = aux3['DESCRICAO_SUBCAT'][cont]
      break
  return disease

  
print(cod_cid('E149'))  #Example

In [ ]:
##  The 10 greatest death causes per year in descending order, bringing the number 
##  of deaths per cause and the percentage related to the total of deaths per year/period.

deaths_per_year = dict()
deaths_per_year_percentage = dict()
df3 = df2.loc[:, ['CAUSABAS', 'ANO_O']]
#display(df3)
years = list(range(2010,2020))
total_per_year = list()

for y in years:
  df3_filtred = df3[df3["ANO_O"] == y]
  deaths_per_year[y]= dict(df3_filtred['CAUSABAS'].value_counts(sort=True))
  total_per_year.append(sum(deaths_per_year[y].values()))

for k1 in deaths_per_year.keys():
  count = 0
  aux = dict()
  for k2,v2 in deaths_per_year[k1].items():
    aux[k2] = v2
    count += 1
    if count == 10:
      break
  deaths_per_year[k1] = aux

print('The 10 greatest death causes per year in descending order')
for k,v in deaths_per_year.items():
  print(f'{k} = {v}')

In [ ]:
## The 10 greatest death causes per year in descending order, bringing the number 
## of deaths per cause and the percentage related to the total of deaths per year/period.
## Graphics

import matplotlib.pyplot as plt

for k,v in deaths_per_year.items():
  illness_legend = list()

  for k2,v2 in deaths_per_year[k].items():
    ill = cod_cid(k2)
    illness_legend.append(f"{k2}: {ill['SUBCATEGORIA']}")

  plt.figure(figsize=(16,8))
  plt.title(f'The 10 highest death causes in {k}')
  plt.xlabel('Death causes in CID codes')
  plt.ylabel(f'Number of deaths')
  plt.bar(deaths_per_year[k].keys(), deaths_per_year[k].values())
  
  x = 5000
  for i in illness_legend:
    plt.text(3, x, i, fontsize='small')
    x = x - 200
  plt.savefig(f'/content/drive/MyDrive/tecnicas_datasus_pe/Images/The 10 highest death causes in {k}.png')

In [ ]:
## Percentage related to the total of deaths per year

for k1 in deaths_per_year.keys():
  cont2 = 0
  deaths_per_year_percentage[k1] = dict(deaths_per_year[k1])
  for k2,v2 in deaths_per_year[k1].items():
    deaths_per_year_percentage[k1][k2] = round((v2/(total_per_year[cont2]/100)),3)
  cont2 += 1

print('Percentage related to the total of deaths in year')
for k,v in deaths_per_year_percentage.items():
  print(f'{k} = {v}')

In [ ]:
# Defining the top 10 causes of death

def merge(list1, list2):
  merged_list = tuple(zip(list1, list2))
  return merged_list

position = ['1º','2º','3º','4º','5º','6º','7º','8º','9º','10º']
ill_top10 = []
CID_position = list(death_cause_order.keys())[:10]
#print(CID_position)
for i in range(0,10):
  z = CID_to_ill(CID_position[i])
  ill_top10.append(z)
#print(ill_top10)
top10_tuple = merge(position, ill_top10)
df_top10 = pd.DataFrame(top10_tuple, columns = ['Posição','Causa da morte'])
df_top10

In [ ]:
## Evaluating the 10 cities with the highest number of registered deaths

cities_ibge = pd.read_excel('/content/drive/MyDrive/tecnicas_datasus_pe/Lista-de-Municípios-com-IBGE-Brasil.xlsx')
cities_pe = cities_ibge[cities_ibge['UF']=='PE']
cities_pe = cities_pe[['IBGE','Município']]
#print(cities_pe)

#Dictionary with the code's city and its name
dict_cities = cities_pe.set_index('IBGE').to_dict()

#Dictionary with the 10 cities in PE with the highest number of deaths
city_death_cases = df2['CODMUNOCOR'].value_counts(sort=True)
dict_top10 = dict(city_death_cases[:10]) #dict with the city's code

cities_pe_top10 = dict() #dict with the city's name
for k in dict_top10.keys():
  cities_pe_top10[dict_cities['Município'][k]] = dict_top10[k]

df_cities = pd.DataFrame(zip(cities_pe_top10.keys(),pd.Series(cities_pe_top10)), \
                         index=position,columns=['Município','Número de mortes'])
df_cities